version: "3.8"

services:
  backend:
    build: .
    restart: always #Restart em caso de falhas
    container_name: dockerguessgame-backend
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_PASSWORD=secretpass
      - FLASK_DB_HOST=postgres
      - FLASK_DB_PORT=5432
      - FLASK_DB_NAME=postgres
    ports:
      - "5000:5000"
    networks:
      - guessgame_network
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: dockerguessgame-frontend
    restart: always #Restart em caso de falhas
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:3000"
    networks:
      - guessgame_network
    depends_on:
      - backend

  postgres:
    image: postgres:13 #Mudar versão em caso de atualização
    container_name: dockerguessgame-db
    restart: always #Restart em caso de falhas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guessgame_network

  nginx:
    image: nginx:1.25.0-alpine #Mudar versão em caso de atualização
    container_name: dockerguessgame-nginx
    restart: always #Restart em caso de falhas
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - guessgame_network
    depends_on:
      - frontend
      - backend

networks:
  guessgame_network:
    driver: bridge

volumes:
  postgres_data:
